{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.react",
    "module": "react-native",
    "version": "0.70.4-alpha.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni-java-only",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "react-native-0.70.4-alpha.2-debug.aar",
          "url": "react-native-0.70.4-alpha.2-debug.aar",
          "size": 32990106,
          "sha512": "3578670ad7ee29c399df743efaa63e26a20296f48e6b8632bd775b509380856799fd0188fca724f2ffe418cf37038a9b9f9f261e8554b35a730aa944812074f1",
          "sha256": "e7628c46e98225cb256fcd749dbb42b0f5b53e86925da2ee5c4472ea0ddd1e63",
          "sha1": "cf9ac8cf1eea5a1d9be0977fe4cc840ef89d7395",
          "md5": "326f49ae0cb760d23944f2e8796a7774"
        }
      ]
    },
    {
      "name": "debugVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni-java-only",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "react-native-0.70.4-alpha.2-debug.aar",
          "url": "react-native-0.70.4-alpha.2-debug.aar",
          "size": 32990106,
          "sha512": "3578670ad7ee29c399df743efaa63e26a20296f48e6b8632bd775b509380856799fd0188fca724f2ffe418cf37038a9b9f9f261e8554b35a730aa944812074f1",
          "sha256": "e7628c46e98225cb256fcd749dbb42b0f5b53e86925da2ee5c4472ea0ddd1e63",
          "sha1": "cf9ac8cf1eea5a1d9be0977fe4cc840ef89d7395",
          "md5": "326f49ae0cb760d23944f2e8796a7774"
        }
      ]
    },
    {
      "name": "debugVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "react-native-0.70.4-alpha.2-debug-sources.jar",
          "url": "react-native-0.70.4-alpha.2-debug-sources.jar",
          "size": 1047674,
          "sha512": "b891ea76d1f07111b7a4a5ff5d6539b3577ac5a68d8a7d9c2148db8ab832775fff1ffb0b72d72cbb94f9bf8ebbe935eb89e59f02b0f3207b7ac64d4995112ab3",
          "sha256": "89bdad2165b1c610211c1ae61dd8ef64310dd9b6347387355a30503132ae5404",
          "sha1": "ed5de313fc99b61072b0a871143fda967fe6b94e",
          "md5": "122419b968a67664dc817b5a12902a7d"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni-java-only",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "react-native-0.70.4-alpha.2-release.aar",
          "url": "react-native-0.70.4-alpha.2-release.aar",
          "size": 12635345,
          "sha512": "fb1a958eb98dd62d0121133fc72ab52e212f44ef4ac4d8efc13f82d5e4899095f503781a0d9ac48c0e9cfdd29f34d6ca328ef74662434211898bb1d28948e8ed",
          "sha256": "2c9752cef2f5c844dd0aa97b510617d87f472cf19d27aca018270f851233a460",
          "sha1": "f62c81243eb740ef0fa68372c5e8de8c9ad6cd36",
          "md5": "a1a8330474f58fd3f668d159862268b9"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni-java-only",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "react-native-0.70.4-alpha.2-release.aar",
          "url": "react-native-0.70.4-alpha.2-release.aar",
          "size": 12635345,
          "sha512": "fb1a958eb98dd62d0121133fc72ab52e212f44ef4ac4d8efc13f82d5e4899095f503781a0d9ac48c0e9cfdd29f34d6ca328ef74662434211898bb1d28948e8ed",
          "sha256": "2c9752cef2f5c844dd0aa97b510617d87f472cf19d27aca018270f851233a460",
          "sha1": "f62c81243eb740ef0fa68372c5e8de8c9ad6cd36",
          "md5": "a1a8330474f58fd3f668d159862268b9"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "react-native-0.70.4-alpha.2-release-sources.jar",
          "url": "react-native-0.70.4-alpha.2-release-sources.jar",
          "size": 1047656,
          "sha512": "ca139d44b69dd31d43c4d84f12f2069f257a81c370758f39ec8ff1cde8b1f6a4245fbe8a67342cdb75cccad80b2d968bf7f8d47fa16dbccc6ce8d0f22a84929c",
          "sha256": "b6ed39ea9138b2516881a3834cf0beb4c6649e3b4940a3f9087f8dd076d3784a",
          "sha1": "9260246755c7b09734fe4cc1e0efe9da49e4b9f2",
          "md5": "2df857d6b39ec91d0609c7768fb5ad43"
        }
      ]
    }
  ]
}
